org.gradle.jvmargs=-Xmx3072m -Xms1024m -Xss1m -XX:MaxMetaspaceSize=384m -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

android.suppressUnsupportedCompileSdk=36
