package com.caipan.music.ui.components

import android.net.Uri
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.caipan.music.model.Song
import com.kyant.backdrop.Backdrop

/** Liquid Glass 版首页：与 HomeScreen 同布局，仅启用玻璃折射材质（isMonetStyle=true）。 */
@Composable
fun LiquidHomeScreen(
    accentColor: Color,
    isLightTheme: Boolean,
    contentText: Color? = null,
    contentMuted: Color? = null,
    onPlaylistsTap: () -> Unit,
    onLocalMusicTap: () -> Unit,
    onSettingsTap: () -> Unit,
    onWebdavTap: () -> Unit = {},
    onPickAvatar: () -> Unit = {},
    onProfileNameChange: (String) -> Unit = {},
    recentSongs: List<Song> = emptyList(),
    allSongs: List<Song> = recentSongs,
    profileName: String = "Muse 用户",
    profileAvatar: Uri? = null,
    listeningTimeMs: Long = 0,
    completedPlays: Int = 0,
    repeatCount: Int = 0,
    onRecentSongTap: (Song) -> Unit = {},
    currentSong: Song? = null,
    isPlaying: Boolean = false,
    onPlayPause: () -> Unit = {},
    onTapPlayer: () -> Unit = {},
    backdrop: Backdrop? = null,
    bottomBarBackdrop: com.kyant.backdrop.Backdrop? = null,
    onlineSearchEnabled: Boolean = false,
    onOnlineSearchTap: () -> Unit = {},
    onLocalMusicBoundsChanged: (androidx.compose.ui.geometry.Rect) -> Unit = {},
    onPlaylistsBoundsChanged: (androidx.compose.ui.geometry.Rect) -> Unit = {},
    onWebdavBoundsChanged: (androidx.compose.ui.geometry.Rect) -> Unit = {},
    selectedTab: Int = 0,
    onSelectedTabChanged: (Int) -> Unit = {},
    isLoading: Boolean = false,
) = HomeScreen(
    accentColor = accentColor,
    isLightTheme = isLightTheme,
    isMonetStyle = true,
    contentText = contentText,
    contentMuted = contentMuted,
    onPlaylistsTap = onPlaylistsTap,
    onLocalMusicTap = onLocalMusicTap,
    onSettingsTap = onSettingsTap,
    onWebdavTap = onWebdavTap,
    onPickAvatar = onPickAvatar,
    onProfileNameChange = onProfileNameChange,
    recentSongs = recentSongs,
    allSongs = allSongs,
    profileName = profileName,
    profileAvatar = profileAvatar,
    listeningTimeMs = listeningTimeMs,
    completedPlays = completedPlays,
    repeatCount = repeatCount,
    onRecentSongTap = onRecentSongTap,
    currentSong = currentSong,
    isPlaying = isPlaying,
    onPlayPause = onPlayPause,
    onTapPlayer = onTapPlayer,
    backdrop = backdrop,
    bottomBarBackdrop = bottomBarBackdrop,
    onlineSearchEnabled = onlineSearchEnabled,
    onOnlineSearchTap = onOnlineSearchTap,
    onLocalMusicBoundsChanged = onLocalMusicBoundsChanged,
    onPlaylistsBoundsChanged = onPlaylistsBoundsChanged,
    onWebdavBoundsChanged = onWebdavBoundsChanged,
    selectedTab = selectedTab,
    onSelectedTabChanged = onSelectedTabChanged,
    isLoading = isLoading
)
